name: ssh-hull
version: '1.0.0'
grade: devel
confinement: devmode
summary: SSH Tunnel Manager
description: |
  A Ruby/GTK3 application to manage ssh hulls.

apps:
  ssh-hull:
    command: desktop-launch $SNAP/bin/ssh-hull
    plugs:
      - home
      - desktop
      - desktop-legacy
      - network
      - x11

parts:
  ssh-hull:
    source: https://github.com/ungtb10d/ssh-hull.git
    source-type: git
    plugin: ruby
    ruby-version: 2.5.5
    after:
      - desktop-gtk3
    build-packages:
      - build-essential
      - libatk1.0-dev
      - libgirepository1.0-dev
      - libpango1.0-dev
      - libgtk-3-dev
    stage-packages:
      - gobject-introspection
      - gir1.2-atk-1.0
      - gir1.2-atspi-2.0
      - gir1.2-freedesktop
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-glib-2.0
      - gir1.2-gtk-3.0
      - gir1.2-pango-1.0
      - adwaita-icon-theme
      - libcanberra-gtk3-0
    override-build: |
      snapcraftctl build
      git checkout snap/snapcraft.yaml
      gem build ssh-hull.gemspec
      gem install ssh-hull-*.gem --env-shebang
